sudo: false
language: node_js
node_js:
  - 5
  - 6
  - 7
  - 8
  - stable
cache:
  bundle: true
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm install codecov nyc
script:
  - ./node_modules/.bin/nyc npm test
after_script:
  - ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
  - ./node_modules/.bin/codecov --token=$CODECOV_TOKEN
